### ISSUE TITLE
Error: spawn arp ENOENT

### ISSUE THREAD

**Issue by neumartin** [suskind/network-list#10]
Hi!

I use node v12.18.3
When run the example I get this error:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn arp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn arp',
  path: 'arp',
  spawnargs: [ '-n', '192.168.11.112' ]
}
```

**Comment by neumartin** [comment]
Work after install sudo apt install net-tools
